export const USER_ADDRESS_CREATE_REQUEST = 'USER_ADDRESS_CREATE_REQUEST'
export const USER_ADDRESS_CREATE_SUCCESS = 'USER_ADDRESS_CREATE_SUCCESS'
export const USER_ADDRESS_CREATE_FAIL = 'USER_ADDRESS_CREATE_FAIL'

export const USER_ADDRESS_DETAILS_REQUEST = 'USER_ADDRESS_DETAILS_REQUEST'
export const USER_ADDRESS_DETAILS_SUCCESS = 'USER_ADDRESS_DETAILS_SUCCESS'
export const USER_ADDRESS_DETAILS_FAIL = 'USER_ADDRESS_DETAILS_FAIL'
export const USER_ADDRESS_DETAILS_RESET = 'USER_ADDRESS_DETAILS_RESET'

export const USER_ADDRESS_MAIN_REQUEST = 'USER_ADDRESS_MAIN_REQUEST'
export const USER_ADDRESS_MAIN_SUCCESS = 'USER_ADDRESS_MAIN_SUCCESS'
export const USER_ADDRESS_MAIN_FAIL = 'USER_ADDRESS_MAIN_FAIL'
export const USER_ADDRESS_MAIN_RESET = 'USER_ADDRESS_MAIN_RESET'

export const USER_ADDRESS_LIST_REQUEST = 'USER_ADDRESS_LIST_REQUEST'
export const USER_ADDRESS_LIST_SUCCESS = 'USER_ADDRESS_LIST_SUCCESS'
export const USER_ADDRESS_LIST_FAIL = 'USER_ADDRESS_LIST_FAIL'
export const USER_ADDRESS_LIST_RESET = 'USER_ADDRESS_LIST_RESET'

export const USER_ADDRESS_DELETE_REQUEST = 'USER_ADDRESS_DELETE_REQUEST'
export const USER_ADDRESS_DELETE_SUCCESS = 'USER_ADDRESS_DELETE_SUCCESS'
export const USER_ADDRESS_DELETE_FAIL = 'USER_ADDRESS_DELETE_FAIL'

export const USER_ADDRESS_UPDATE_REQUEST = 'USER_ADDRESS_UPDATE_REQUEST'
export const USER_ADDRESS_UPDATE_SUCCESS = 'USER_ADDRESS_UPDATE_SUCCESS'
export const USER_ADDRESS_UPDATE_FAIL = 'USER_ADDRESS_UPDATE_FAIL'
export const USER_ADDRESS_UPDATE_RESET = 'USER_ADDRESS_UPDATE_RESET'