apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-expiration
  template:
    metadata:
      labels:
        app: shop-expiration
    spec:
      containers:
        - name: shop-expiration
          image: tolhah/shop-expiration:latest
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shop
            - name: REDIS_HOST
              value: shop-expiration-redis-srv
