apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-frontend
  template:
    metadata:
      labels:
        app: shop-frontend
    spec:
      containers:
        - name: shop-frontend
          image: tolhah/shop-frontend:latest
---
apiVersion: v1
kind: Service
metadata:
  name: shop-frontend-srv
spec:
  selector:
    app: shop-frontend
  ports:
    - name: shop-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
