name: tests-notifications

on: 
  pull_request:
    paths:
      - 'notifications/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd notifications && npm install
